name: Terraform Auto-Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render Terraform Documentation and push changes - PR
        if: github.event_name == 'pull_request'
        uses: terraform-docs/gh-actions@v1.2.2
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Render Terraform Documentation and push changes - Push
        if: github.event.ref == 'refs/heads/main'
        uses: terraform-docs/gh-actions@v1.2.2
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
