name: Terraform Auto-Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render Terraform Documentation and push changes - PR
        uses: terraform-docs/gh-actions@v1.2.2
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
